version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: nestjs_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-postgres}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - db
    networks:
      - app-network
    command: npm run start:prod

volumes:
  postgres_data:

networks:
  app-network: